import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "./tailwind.css"; // generated by tailwind CLI (run `npm run tailwind:watch`)

createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
